<?php
/**
 * @file
 * Main module file for the og_tasks module.
 */

define('OG_TASKS_COMPLETED', 'completed');
define('OG_TASKS_REQUIRED', 'required');
define('OG_TASKS_OPTIONAL', 'optional');

/**
 * Implementation of hook_menu().
 */
function og_tasks_menu() {
  $items = array();

  $items['group/%/%/admin/tasks'] = array(
    'title' => 'Group tasks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_tasks_form', 1, 2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin.inc',
    'weight' => 5,
    'access callback' => 'og_user_access_by_entity',
    'access arguments' => array('run og tasks', 1, 2),
  );

  return $items;
}

/**
 * Implement hook_og_permission().
 */
function og_tasks_og_permission() {
  $items = array();

  $items['run og tasks'] = array(
    'title' => t('Run group tasks'),
    'description' => t("Perform tasks for the group."),
    'default role' => array(OG_ADMINISTRATOR_ROLE),
  );

  return $items;
}

/**
 * Implementation of hook_og_ui_get_group_admin()
 */
function og_tasks_og_ui_get_group_admin($gid) {
  $items = array();

  $default_access = og_is_group_default_access($gid);

  $items['tasks'] = array(
    'title' => t('Tasks'),
    'description' => t('Common tasks to be run for this group.'),
    'href' => 'admin/tasks',
  );

  return $items;
}

/**
 * Return a list of tasks for the given group.
 */
function og_tasks_get_tasks($entity_type, $entity) {
  $tasks = array();
  $info = module_invoke_all('og_tasks_info', $entity_type, $entity);
  foreach ($info as $key => $task) {
    if (is_a($task, 'og_task')) {
      $task->key = $key;
      $tasks[$key] = $task;
    }
  }
  return $tasks;
}

/**
 * Implements hook_admin_paths().
 */
function og_tasks_admin_paths() {
  return array(
    'group/*/*/admin/*' => TRUE,
  );
}

